import os


BASE_DIR = os.path.dirname(os.path.abspath(__file__))


class Config:
    SECRET_KEY = "secret123"
    SQLALCHEMY_DATABASE_URI = "sqlite:///" + os.path.join(BASE_DIR, "users.db")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    DEFAULT_SYMBOLS = [
        "RELIANCE.NS",
        "TCS.NS",
        "INFY.NS",
        "HDFCBANK.NS",
        "ICICIBANK.NS",
        "SBIN.NS",
        "ITC.NS",
        "LT.NS",
        "MARUTI.NS",
        "TATAMOTORS.NS",
        "AXISBANK.NS",
        "BHARTIARTL.NS",
        "ASIANPAINT.NS",
        "SUNPHARMA.NS",
        "WIPRO.NS",
        "HCLTECH.NS",
        "Reliance Industries Ltd.NS",
    "HDFCBANK.NS",
    "BHARTIARTL.NS",
    "TCS.NS",
    "SBIN.NS",
    "ICICIBANK.NS",
    "BAJFINANCE.NS",
    "INFY.NS",
    "LT.NS",
    "HINDUNILVR.NS",
    "LICI.NS",
    "MARUTI.NS",
    "M&M.NS",
    "SUNPHARMA.NS",
    "ITC.NS",
    "AXISBANK.NS",
    "KOTAKBANK.NS",
    "HCLTECH.NS",
    "TITAN.NS",
    "NTPC.NS",
    "ULTRACEMCO.NS",
    "ADANIPORTS.NS",
    "ONGC.NS",
    "ADANIPOWER.NS",
    "BEL.NS",
    "BAJAJFINSV.NS",
    "JSWSTEEL.NS",
    "HAL.NS",
    "ADANIENT.NS",
    "BAJAJ-AUTO.NS",
    "POWERGRID.NS",
    "COALINDIA.NS",
    "DMART.NS",
    "ETERNAL.NS",
    "HINDZINC.NS",
    "NESTLEIND.NS",
    "TATASTEEL.NS",
    "ASIANPAINT.NS",
    "VEDL.NS",
    "WIPRO.NS",
    "IOC.NS",
    "HINDALCO.NS",
    "EICHERMOT.NS",
    "SBILIFE.NS",
    "SHRIRAMFIN.NS",
    "GRASIM.NS",
    "INDIGO.NS",
    "TVSMOTOR.NS",
    "ADANIGREEN.NS",
    "HYUNDAI.NS",
    "DIVISLAB.NS",
    "JIOFIN.NS",
    "VBL.NS",
    "TATAMOTORS.NS",
    "DLF.NS",
    "LTM.NS",
    "TECHM.NS",
    "BANKBARODA.NS",
    "HDFCLIFE.NS",
    "BPCL.NS",
    "PIDILITIND.NS",
    "MUTHOOTFIN.NS",
    "TRENT.NS",
    "IRFC.NS",
    "BRITANNIA.NS",
    "TORNTPHARM.NS",
    "CHOLAFIN.NS",
    "PNB.NS",
    "PFC.NS",
    "UNIONBANK.NS",
    "ADANIENSOL.NS",
    "CUMMINSIND.NS",
    "CANBK.NS",
    "MOTHERSON.NS",
    "SOLARINDS.NS",
    "ABB.NS",
    "TATAPOWER.NS",
    "AMBUJACEM.NS",
    "BAJAJHLDNG.NS",
    "POLYCAB.NS",
    "SIEMENS.NS",
    "IDEA.NS",
    "INDIANB.NS",
    "JINDALSTEL.NS",
    "GODREJCP.NS",
    "TATACONSUM.NS",
    "INDUSTOWER.NS",
    "HDFCAMC.NS",
    "CGPOWER.NS",
    "CIPLA.NS",
    "HEROMOTOCO.NS",
    "POWERINDIA.NS",
    "APOLLOHOSP.NS",
    "GAIL.NS",
    "DRREDDY.NS",
    "BOSCHLTD.NS",
    "ASHOKLEY.NS",
    "BHEL.NS",
    "GMRAIRPORT.NS",
    "LUPIN.NS",
    "SIEMENS.NS",
    "MAXHEALTH.NS",
    "MARICO.NS",
    "MAZDOCK.NS",
    "UNITDSPR.NS",
    "IDBI.NS",
    "LODHA.NS",
    "INDHOTEL.NS",
    "ICICIGI.NS",
    "ZYDUSLIFE.NS",
    "RECLTD.NS",
    "SHREECEM.NS",
    "MANKIND.NS",
    "ABCAPITAL.NS",
    "HINDPETRO.NS",
    "JSWENERGY.NS",
    "PERSISTENT.NS",
    "ICICIPRULI.NS",
    "SWIGGY.NS",
    "WAAREEENER.NS",
    "DABUR.NS",
    "HAVELLS.NS",
    "NTPCGREEN.NS",
    "SRF.NS",
    "BHARTIHEXA.NS",
    "BHARATFORG.NS",
    "NHPC.NS",
    "POLICYBZR.NS",
    "PAYTM.NS",
    "OIL.NS",
    "AUROPHARMA.NS",
    "BAJAJHFL.NS",
    "LLOYDSME.NS",
    "NYKAA.NS",
    "NAUKRI.NS",
    "AUBANK.NS",
    "NMDC.NS",
    "TORNTPOWER.NS",
    "LTF.NS",
    "SBICARD.NS",
    "DIXON.NS",
    "INDUSINDBK.NS",
    "BANKINDIA.NS",
    "FEDERALBNK.NS",
    "OFSS.NS",
    "FORTIS.NS",
    "NATIONALUM.NS",
    "UNOMINDA.NS",
    "IOB.NS",
    "SUZLON.NS",
    "GICRE.NS",
    "ALKEM.NS",
    "YESBANK.NS",
    "SAIL.NS",
    "MCX.NS",
    "IDFCFIRSTB.NS",
    "RVNL.NS",
    "JSL.NS",
    "COROMANDEL.NS",
    "ATGL.NS",
    "PRESTIGE.NS",
    "PHOENIXLTD.NS",
    "SCHAEFFLER.NS",
    "GLENMARK.NS",
    "BIOCON.NS",
    "MRF.NS",
    "NAM-INDIA.NS",
    "LAURUSLABS.NS",
    "UPL.NS",
    "OBEROIRLTY.NS",
    "MFSL.NS",
    "ABBOTINDIA.NS",
    "COLPAL.NS",
    "LINDEINDIA.NS",
    "BERGEPAINT.NS",
    "JSWINFRA.NS",
    "APLAPOLLO.NS",
    "PATANJALI.NS",
    "GODREJPROP.NS",
    "MAHABANK.NS",
    "TIINDIA.NS",
    "HINDCOPPER.NS",
    "BDL.NS",
    "COFORGE.NS",
    "MOTILALOFS.NS",
    "M&MFIN.NS",
    "IRCTC.NS",
    "MPHASIS.NS",
    "PIIND.NS",
    "TATACOMM.NS",
    "SUPREMEIND.NS",
    "VOLTAS.NS",
    "BALKRISIND.NS",
    "360ONE.NS",
    "KALYANKJIL.NS",
    "AUTHUM.NS",
    "KEI.NS",
    "JKCEMENT.NS",
    "PETRONET.NS",
    "GLAXO.NS",
    "ASTRAL.NS",
    "UBL.NS",
    "RADICO.NS",
    "HUDCO.NS",
    "COCHINSHIP.NS",
    "THERMAX.NS",
    "APARINDS.NS",
    "LTTS.NS",
    "PREMIERENE.NS",
    "PAGEIND.NS",
    "NLCINDIA.NS",
    "IPCALAB.NS",
    "ESCORTS.NS",
    "CONCOR.NS",
    "FLUOROCHEM.NS",
    "DALBHARAT.NS",
    "NH.NS",
    "BLUESTARCO.NS",
    "IREDA.NS",
    "AIAENG.NS",
    "POONAWALLA.NS",
    "AJANTPHARM.NS",
    "HEXAWARE.NS",
    "GODFRYPHLP.NS",
    "ENDURANCE.NS",
    "UCOBANK.NS",
    "TATAINVEST.NS",
    "ASTERDM.NS",
    "GODREJIND.NS",
    "JUBLFOOD.NS",
    "CENTRALBK.NS",
    "SONACOMS.NS",
    "NAVINFLUOR.NS",
    "DELHIVERY.NS",
    "CRISIL.NS",
    "JBMA.NS",
    "KPRMILL.NS",
    "MEDANTA.NS",
    "TATAELXSI.NS",
    "MRPL.NS",
    "GLAND.NS",
    "ACC.NS",
    "SJVN.NS",
    "APOLLOTYRE.NS",
    "LICHSGFIN.NS",
    "EMCURE.NS",
    "EXIDEIND.NS",
    "TVSHLTD.NS",
    "GRSE.NS",
    "METROBRAND.NS",
    "MSUMI.NS",
    "HONAUT.NS",
    "STARHEALTH.NS",
    "ITI.NS",
    "ZFCVINDIA.NS",
    "IKS.NS",            
    "AWL.NS",            
    "FORCEMOT.NS",       
    "KIMS.NS",           
    "BANDHANBNK.NS",     
    "GUJGASLTD.NS",      
    "NBCC.NS",           
    "ANANDRATHI.NS",     
    "GILLETTE.NS",       
    "ABSLAMC.NS",        
    "PTCIL.NS",          
    "KAYNES.NS",         
    "IRB.NS",            
    "TATATECH.NS",       
    "NIACL.NS",          
    "AMBER.NS",          
    "KPITTECH.NS",       
    "HIMATSEIDE.NS",     
    "NUVAMA.NS",         
    "MANAPPURAM.NS",     
    "TIMKEN.NS",         
    "WELCORP.NS",        
    "AEGISLOG.NS",       
    "ANGELONE.NS",       
    "RAMCOCEM.NS",       
    "LALPATHLAB.NS",     
    "IGL.NS",            
    "AEGISVOPAK.NS",     
    "PNBHOUSING.NS",     
    "SHYAMMETL.NS",      
    "ASAHIINDIA.NS",     
    "PINELABS.NS",       
    "WOCKPHARMA.NS",     
    "SUNTV.NS",          
    "PFIZER.NS",         
    "TENNECO.NS",        
    "KIOCL.NS",          
    "IIFL.NS",           
    "DEEPAKNTR.NS",      
    "CESC.NS",           
    "AFFLE.NS",          
    "SCHNEIDER.NS",      
    "SUMICHEM.NS",       
    "PPLPHARMA.NS",      
    "ASTRAZEN.NS",       
    "HBLENGINE.NS",      
    "SAGILITY.NS",       
    "ADITYAINFO.NS",     
    "HATSUN.NS",         
    "EIHOTEL.NS",        
    "AADHARHFC.NS",      
    "EMAMILTD.NS",       
    "BAYERCROP.NS",      
    "CREDITACC.NS",      
    "SAILIFE.NS",        
    "PFOCUS.NS",         
    "KIRLOSENG.NS",      
    "SYNGENE.NS",        
    "CUB.NS",            
    "KPIL.NS",           
    "NETWEB.NS",         
    "ERIS.NS",           
    "GESHIP.NS",         
    "RBLBANK.NS",        
    "REDINGTON.NS",      
    "FSL.NS",            
    "GMDCLTD.NS",        
    "NSDL.NS",           
    "ATUL.NS",           
    "BRIGADE.NS",        
    "JYOTICNC.NS",       
    "URBANCO.NS",        
    "NEULANDLAB.NS",     
    "ANANTRAJ.NS",       
    "SARDAEN.NS",        
    "TATACHEM.NS",       
    "SUNDRMFAST.NS",     
    "PSB.NS",            
    "CASTROLIND.NS",     
    "CRAFTPAPER.NS",     
    "CAMS.NS",           
    "JSWHL.NS",          
    "DCMSHRIRAM.NS",     
    "GPIL.NS",           
    "CHALET.NS",         
    "CHAMBLFERT.NS",     
    "ONESOURCE.NS",      
    "INOXWIND.NS",       
    "GRINDWELL.NS",      
    "ECLERX.NS",         
    "DATAPATTNS.NS",     
    "NATCOPHARM.NS",     
    "CGCL.NS",           
    "RRKABEL.NS",        
    "CENTURYPLY.NS",     
    "KANSAINER.NS",      
    "CIEINDIA.NS",       
    "KFINTECH.NS",       
    "BIKAJI.NS",         
    "BELRISE.NS",        
    "TRITURBINE.NS",     
    "NAVA.NS",           
    "RATNAMANI.NS",      
    "CARBORUNIV.NS",     
    "CROMPTON.NS",       
    "KEC.NS",            
    "KAJARIACER.NS",     
    "SYRMA.NS",          
    "VENTIVE.NS",        
    "BASF.NS",           
    "ELGIEQUIP.NS",      
    "EIDPARRY.NS",       
    "CHOICEIN.NS",       
    "ABREL.NS",          
    "PGEL.NS",           
    "LMW.NS",            
    "ARE&M.NS",          
    "POLYMED.NS",        
    "IFCI.NS",           
    "JUBLPHARMA.NS",     
    "AVANTIFEED.NS",     
    "AARTIIND.NS",       
    "GRANULES.NS",       
    "APLLTD.NS",         
    "SOBHA.NS",          
    "DEVYANI.NS",        
    "GALLANTT.NS",       
    "MAHSCOOTER.NS",     
    "VINATIORGA.NS",     
    "TBOTEK.NS",         
    "VTL.NS",            
    "ANURAS.NS",         
    "CEATLTD.NS",        
    "AGARWALEYE.NS",     
    "OLAELEC.NS",        
    "DEEPAKFERT.NS",     
    "DOMS.NS",           
    "BEML.NS",           
    "ZYDUSWELL.NS",      
    "VGUARD.NS",         
    "NIVABUPA.NS",       
    "GABRIEL.NS",        
    "IRCON.NS",          
    "CHENNPETRO.NS",     
    "JBMA.NS",           
    "ZENSARTECH.NS",     
    "SHRIPISTON.NS",     
    "FIVESTAR.NS",       
    "TDPOWERSYS.NS",     
    "LTFOODS.NS",        
    "KSB.NS",            
    "CCL.NS",           
    "CAPLIPOINT.NS",     
    "AETHER.NS",         
    "FINEORG.NS",        
    "USHAMART.NS",       
    "MINDACORP.NS",      
    "UTIAMC.NS",         
    "FIRSTCRY.NS",       
    "SANSERA.NS",        
    "FINCABLES.NS",      
    "TRIDENT.NS",        
    "PARADEEP.NS",       
    "SIGNATURE.NS",      
    "JKTYRE.NS",         
    "HFCL.NS",           
    "TECHNOE.NS",        
    "ZENTEC.NS",         
    "TEGA.NS",           
    "INDIAMART.NS",      
    "APTUS.NS",          
    "INDIACEM.NS",       
    "JMFINANCIL.NS",     
    "BLUEDART.NS",       
    "KIRLOSBROS.NS",     
    "GRAPHITE.NS",       
    "CONCORDBIO.NS",     
    "SUPPETRO.NS",       
    "WELSPUNLIV.NS",     
    "AFCONS.NS",         
    "JINDALSAW.NS",      
    "JWL.NS",            
    "MTARTECH.NS",       
    "GRAVITA.NS",        
    "RPOWER.NS",         
    "INDEGENE.NS",       
    "SCI.NS",            
    "CANFINHOME.NS",     
    "PRIVISCL.NS",       
    "NUVOCO.NS",         
    "ENGINERSIN.NS",     
    "BLS.NS",            
    "IEX.NS",            
    "JPPOWER.NS",        
    "HOMEFIRST.NS",      
    "HAPPYFORGE.NS",     
    "VEDLIFE.NS",        
    "THANGAMAYL.NS",     
    "PCBL.NS",           
    "INOXINDIA.NS",      
    "GODREJAGRO.NS",     
    "WHIRLPOOL.NS",      
    "INTELLECT.NS",      
    "UJJIVANSFB.NS",     
    "CYIENT.NS",         
    "AZAD.NS",           
    "HEG.NS",            
    "BSOFT.NS",          
    "BLACKBUCK.NS",      
    "LUMAXTECH.NS",      
    "FINPIPE.NS",        
    "MGL.NS",            
    "AAVAS.NS",          
    "VIJAYA.NS",         
    "ACE.NS",            
    "EDELWEISS.NS",      
    "SBFC.NS",           
    "JUBLINGREA.NS",     
    "PRUDENT.NS",        
    "RITES.NS",          
    "SOUTHBANK.NS",      
    "BATAINDIA.NS",      
    "RAILTEL.NS",        
    "CARTRADE.NS",       
    "SHAILY.NS",         
    "CELLO.NS",          
    "TITAGARH.NS",       
    "EUREKAFORB.NS",     
    "LEMONTREE.NS",      
    "MEDPLUS.NS",        
    "ELECON.NS",         
    "IIFLCAPS.NS",       
    "TILIND.NS",         
    "BBOX.NS",           
    "METROPOLIS.NS",     
    "HONASA.NS",         
    "PVRINOX.NS",        
    "VESUVIUS.NS",       
    "TMB.NS",            
    "RKFORGE.NS",        
    "WAAREERTL.NS",      
    "NAZARA.NS",         
    "NCC.NS",            
    "STLTECH.NS",
"Zee Entertainment Enterprises Ltd..NS",
"Jeena Sikho Lifecare Limited.NS",
"EMBASSY DEVELOPMENTS LIMITED.NS",
"Karnataka Bank Ltd..NS",
"Marksans Pharma Ltd..NS",
"Nesco Ltd.NS",
"KPI Green Energy Limited.NS",
"Orkla India Limited.NS",
"Aditya Birla Fashion and Retail Limited.NS",
"Triveni Engineering & Industries Ltd.NS",
"Sonata Software Ltd..NS",
"Amagi Media Labs Limited.NS",
"LLOYDS ENTERPRISES LIMITED.NS",
"Jayaswal Neco Industries Ltd.NS",
"GMR Power and Urban Infra Limited.NS",
"Gujarat Pipavav Port Limited.NS",
"Manorama Industries Limited.NS",
"VA Tech Wabag Limited.NS",
"KRBL Ltd..NS",
"P N GADGIL JEWELLERS LIMITED.NS",
"SHADOWFAX TECHNOLOGIES LIMITED.NS",
"VIYASH SCIENTIFIC LIMITED.NS",
"Alkyl Amines Chemicals Ltd..NS",
"SEDEMAC MECHATRONICS LIMITED.NS",
"Kirloskar Pneumatic Co.Ltd..NS",
"WESTLIFE FOODWORLD LIMITED.NS",
"Vikram Solar Limited.NS",
"Blue Jet Healthcare Limited.NS",
"Campus Activewear Limited.NS",
"Maharashtra Seamless Ltd..NS",
"Transport Corporation of India Ltd.NS",
"Birla Corporation Ltd..NS",
"Mahindra Lifespace Developers Ltd..NS",
"V2 Retail Limited.NS",
"Religare Enterprises Ltd.NS",
"Diamond Power Infrastructure Limited.NS",
"Latent View Analytics Limited.NS",
"Akums Drugs and Pharmaceuticals Limited.NS",
"TTK Prestige Ltd..NS",
"Tejas Networks Limited.NS",
"WeWork India Management Limited.NS",
"BlueStone Jewellery and Lifestyle Limited.NS",
"Equitas Small Finance Bank Limited.NS",
"Dilip Buildcon Limited.NS",
"Indian Metals & Ferro Alloys Limited.NS",
"Bengal & Assam Company Limited.NS",
"Shakti Pumps (India) Ltd..NS",
"Transrail Lighting Limited.NS",
"Pearl Global Industries Limited.NS",
"PC JEWELLER LIMITED.NS",
"Rashtriya Chemicals & Fertilizers Limited.NS",
"Pricol Limited.NS",
"Alok Industries Ltd..NS",
"TIPS MUSIC LIMITED.NS",
"Sudeep Pharma Limited.NS",
"Kirloskar Ferrous Industries Ltd..NS",
"RateGain Travel Technologies Limited.NS",
"Elantas Beck India Ltd.NS",
"Sudarshan Chemical Indus. Ltd..NS",
"Power Mech Projects Limited.NS",
"Sri Lotus Developers and Realty Limited.NS",
"CSB Bank Limited.NS",
"Shilpa Medicare Ltd..NS",
"Archean Chemical Industries Limited.NS",
"QUALITY POWER ELECTRICAL EQUIPMENTS LIMITED.NS",
"Fujiyama Power Systems Limited.NS",
"Gujarat Narmada Valley Fert.Co.Ltd.NS",
"BOROSIL RENEWABLES LIMITED.NS",
"Dodla Dairy Limited.NS",
"REDTAPE Limited.NS",
"ETHOS LIMITED.NS",
"Gujarat State Fertilizers & Chem.Ltd.NS",
"EPL LIMITED.NS",
"Avalon Technologies Limited.NS",
"INOX GREEN ENERGY SERVICES LIMITED.NS",
"Kalpataru Limited.NS",
"Welspun Enterprises Limited.NS",
"YATHARTH HOSPITAL & TRAUMA CARE SERVICES LIMITED.NS",
"Saregama India Ltd..NS",
"Thyrocare Technologies Limited.NS",
"Dynamatic Technologies Ltd..NS",
"Cera Sanitaryware Ltd..NS",
"ISGEC Heavy Engineering Limited.NS",
"Galaxy Surfactants Limited.NS",
"Max Estates Limited.NS",
"LLOYDS ENGINEERING WORKS LIMITED.NS",
"C.E. Info Systems Limited.NS",
"Mishra Dhatu Nigam Limited.NS",
"TANLA PLATFORMS LIMITED.NS",
"AXISCADES TECHNOLOGIES LIMITED.NS",
"Aarti Pharmalabs Limited.NS",
"Mrs. Bectors Food Specialities Limited.NS",
"MOIL Limited.NS",
"Aditya Vision Limited.NS",
"GARWARE TECHNICAL FIBRES LIMITED.NS",
"PRISM JOHNSON LIMITED..NS",
"Sapphire Foods India Limited.NS",
"Gujarat Ambuja Exports Ltd..NS",
"India Glycols Ltd.NS",
"Jai Balaji Industries Limited.NS",
"Ashapura Minechem Ltd.NS",
"Happiest Minds Technologies Limited.NS",
"Kwality Wall’s (India) Limited.NS",
"FDC Ltd..NS",
"Arvind Fashions Limited.NS",
"Powerica Ltd..NS",
"Praj Industries Ltd..NS",
"Shreeji Shipping Global Limited.NS",
"VALOR ESTATE LIMITED.NS",
"AJAX Engineering Limited.NS",
"Sheela Foam Limited.NS",
"Greenlam Industries Ltd.NS",
"Hindustan Foods Ltd..NS",
"Kovai Medical Center & Hospital Ltd.NS",
"Suprajit Engineering Ltd..NS",
"Kingfa Science & Technology (India) Ltd.NS",
"JK Paper Ltd..NS",
"GANESH HOUSING LIMITED.NS",
"DCB Bank Limited.NS",
"FIEM INDUSTRIES LIMITED.NS",
"SML Mahindra Limited.NS",
"MAS Financial Services Limited.NS",
"Sky Gold And Diamonds Limited.NS",
"BALU FORGE INDUSTRIES LIMITED.NS",
"Keystone Realtors Limited.NS",
"Ahluwalia Contracts (India) Ltd.NS",
"Symphony Limited.NS",
"L.g.Balkrishnan & Bros. Ltd..NS",
"Piccadily Agro Industries ltd..NS",
"Paras Defence and Space Technologies Limited.NS",
"Mastek Limited.NS",
"Network 18 Media & Investments Limited.NS",
"Gokul Agro Resources Ltd.NS",
"PNC Infratech Limited.NS",
"S.J.S. Enterprises Limited.NS",
"KRN HEAT EXCHANGER AND REFRIGERATION LIMITED.NS",
"Mahindra Holidays & Resorts India Limited.NS",
"Supriya Lifescience Limited.NS",
"Precision Wires India ltd..NS",
"ICRA Limited.NS",
"Wakefit Innovations Limited.NS",
"Raymond Lifestyle Limited.NS",
"Shree Renuka Sugars Ltd..NS",
"Ion Exchange (India) Ltd.NS",
"Fedbank Financial Services Limited.NS",
"Nephrocare Health Services Limited.NS",
"Indo Count Industries Ltd.NS",
"Sunteck Realty Ltd.NS",
"Thomas Cook (India) Ltd..NS",
"SG MART LIMITED.NS",
"AvenuesAI Limited.NS",
"Senco Gold Limited.NS",
"Surya Roshni Ltd..NS",
"Canara Robeco Asset Management Company Limited.NS",
"Pilani Investment And Industries Corporation Limited.NS",
"Puravankara Limited.NS",
"Just Dial Limited.NS",
"Technocraft Industries (India) Ltd..NS",
"Gulf Oil Lubricants India Limited.NS",
"CMS Info Systems Limited.NS",
"Saatvik Green Energy Limited.NS",
"PTC India Ltd.NS",
"Aurionpro Solutions Ltd.NS",
"Gokaldas Exports Ltd.NS",
"Subros Ltd..NS",
"Midwest Gold Ltd.NS",
"Kennametal India Limtied.NS",
"Rallis India Ltd.NS",
"Lumax Industries Ltd..NS",
"Sharda Motor Industries Ltd..NS",
"Jamna Auto Industries Ltd..NS",
"SMARTWORKS COWORKING SPACES LIMITED.NS",
"Ceigall India Limited.NS",
"V-Mart Retail Limited.NS",
"IFB Industries Limited.NS",
"Juniper Hotels Limited.NS",
"Midwest Limited.NS",
"Hindustan Construction Co. Ltd..NS",
"Entero Healthcare Solutions Limited.NS",
"Dhanuka Agritech Ltd..NS",
"V.I.P. Industries Ltd..NS",
"BAJAJ CONSUMER CARE LIMITED.NS",
"Epigral Limited.NS",
"Sunflag Iron & Steel Co. Ltd..NS",
"RattanIndia Power Limited.NS",
"RATTANINDIA ENTERPRISES LIMITED.NS",
"TVS Supply Chain Solutions Limited.NS",
"CARE Ratings Limited.NS",
"GHCL Ltd..NS",
"Indigo Paints Limited.NS",
"V.S.T.Tillers Tractors Ltd..NS",
"Nirlon Limited.NS",
"NIIT Learning Systems Limited.NS",
"Electrosteel Castings Ltd..NS",
"SIS LIMITED.NS",
"Responsive Industries Ltd.NS",
"Bajaj Electricals Ltd..NS",
"Unimech Aerospace and Manufacturing Limited.NS",
"STERLING AND WILSON RENEWABLE ENERGY LIMITED.NS",
"Skipper Limited.NS",
"India Tourism Development Corporati.NS",
"Oswal Pumps Limited.NS",
"Kaveri Seed Company Ltd.NS",
"Texmaco Rail & Engineering Limited.NS",
"Capillary Technologies India Limited.NS",
"Sun Pharma Advanced Research Company Ltd..NS",
"VRL Logistics Limited.NS",
"Rain Industries Limited.NS",
"Shilchar Technologies Ltd..NS",
"MAN INFRACONSTRUCTION LIMITED.NS",
"Bannari Amman Sugars Ltd..NS",
"Bansal Wire Industries Limited.NS",
"PDS LIMITED.NS",
"Reliance Infrastructure Ltd.NS",
"Swaraj Engines Ltd..NS",
"Datamatics Global Services Limited.NS",
"Rajesh Exports Ltd..NS",
"JANA SMALL FINANCE BANK LIMITED.NS",
"GMM Pfaudler Ltd..NS",
"TARC LIMITED.NS",
"Knowledge Marine & Engineering Works Limited.NS",
"TANFAC Industries Ltd..NS",
"ASM Technologies Ltd..NS",
"Omnitech Engineering Limited.NS",
"Suven Life Sciences Ltd..NS",
"Seshaasai Technologies Limited.NS",
"INNOVA CAPTAB LIMITED.NS",
"CRIZAC LIMITED.NS",
"H.G. Infra Engineering Limited.NS",
"Northern Arc Capital Ltd..NS",
"VST Industries Ltd..NS",
"Gujarat Alkalis & Chemicals Ltd..NS",
"D.B.Corp Limited.NS",
"Laxmi Organic Industries Limited.NS",
"Chemplast Sanmar Limited.NS",
"Goldiam International Ltd..NS",
"Hawkins Cooker Ltd..NS",
"J. Kumar Infraprojects Limited.NS",
"GNG Electronics Limited.NS",
"AGI GREENPAC LIMITED.NS",
"Ashoka Buildcon Limited.NS",
"Electronics Mart India Limited.NS",
"Avantel Limited.NS",
"WPIL Ltd.NS",
"eMudhra Limited.NS",
"TechNVision Ventures Limited.NS",
"Balaji Amines Ltd..NS",
"OnEMI Technology Solutions Limited.NS",
"The Anup Engineering Ltd.NS",
"SENORES PHARMACEUTICALS LIMITED.NS",
"Artemis Medicare Services Limited.NS",
"National Fertilizers Ltd..NS",
"Pondy Oxides & Chemicals Limited.NS",
"Pace Digitek Limited.NS",
"R Systems International Limited.NS",
"Stylam Industries Limited.NS",
"Greaves Cotton Ltd..NS",
"Hemisphere Properties India Limited.NS",
"Centum Electronics Ltd.NS",
"Shoppers Stop Ltd.NS",
"KNR Constructions Limited.NS",
"ELLENBARRIE INDUSTRIAL GASES LIMITED.NS",
"Goodluck India Limited.NS",
"JTEKT India Limited.NS",
"Indraprastha Medical Corporation Lt.NS",
"Orient Electric Limited.NS",
"Optiemus Infracom Limited.NS",
"Gujarat Themis Biosyn Ltd..NS",
"AGI Infra Limited.NS",
"MOSCHIP TECHNOLOGIES LIMITED.NS",
"BOSCH HOME COMFORT INDIA LIMITED.NS",
"Vaibhav Global Ltd.NS",
"Restaurant Brands Asia Limited.NS",
"INDIQUBE SPACES LIMITED.NS",
"Gopal Snacks Limited.NS",
"HeidelbergCement India Limited.NS",
"Bondada Engineering Limited.NS",
"ZAGGLE PREPAID OCEAN SERVICES LIMITED.NS",
"Samhi Hotels Limited.NS",
"CIAN Agro Industries & Infrastructure Limited.NS",
"RAGHAV PRODUCTIVITY ENHANCERS LIMITED.NS",
"Indo Thai Securities Limited.NS",
"NACL Industries Limited.NS",
"Vishnu Chemicals Limited.NS",
"Styrenix Performance Materials Limited.NS",
"Sanathan Textiles Limited.NS",
"Websol Energy System Limited.NS",
"Mahindra Logistics Limited.NS",
"TRUALT BIOENERGY LIMITED.NS",
"Foseco India Ltd.NS",
"Neogen Chemicals Limited.NS",
"Route Mobile Limited.NS",
"COLAB PLATFORMS LIMITED.NS",
"Rolex Rings Limited.NS",
"ANAND RATHI SHARE AND STOCK BROKERS LIMITED.NS",
"Sindhu Trade Links Limited.NS",
"PAISALO DIGITAL LIMITED.NS",
"RPG Life Sciences Limited.NS",
"Shanthi Gears Ltd..NS",
"Heritage Foods Limited.NS",
"Kitex Garmenets Ltd..NS",
"Advanced Enzyme Technologies Limited.NS",
"Aarti Drugs Limited.NS",
"Harsha Engineers International Limited.NS",
"Refex Industries Limited.NS",
"Ramky Infrastructure Limited.NS",
"Orchid Pharma Limited.NS",
"SMS Pharmaceuticals Ltd.NS",
"IndoStar Capital Finance Limited.NS",
"LUX Industries Limited",
"Vadilal Industries Ltd.",
"Interarch Building Solutions Limited",
"Seamec Ltd",
"Wonderla Holidays Limited",
"Flair Writing Industries Limited",
"Marathon Nextgen Realty Ltd",
"Kirloskar Industries Ltd",
"ENVIRO INFRA ENGINEERS LIMITED",
"Kolte-Patil Developers Ltd",
"Kalyani Steels Ltd",
"Man Industries (India) Ltd",
"Uflex Limited",
"Timex Group India Ltd",
"MSTC Limited",
"Share India Securities Limited",
"PITTI ENGINEERING LIMITED",
"KESAR INDIA LIMITED",
"Tourism Finance Corpn. Of India Ltd",
"Aeroflex Industries Limited",
"Steel Strips & Wheels Ltd",
"Ashiana Housing Limited",
"Navneet Education Limited",
"Ram Ratna Wires Ltd.",
"Sandhar Technologies Limited",
"KSH INTERNATIONAL LIMITED",
"Grauer & Weil (India) Ltd.",
"Dishman Carbogen Amcis Limited",
"Raymond Realty Limited",
"ORIENT CEMENT LIMITED",
"Hubtown Limited",
"Gufic BioSciences Ltd.",
"PSP Projects Limited",
"Borosil Limited",
"Nalwa Sons Investment Ltd",
"63 Moons Technologies Limited",
"TVS Srichakra Ltd.",
"Balmer Lawrie & Co. Ltd.",
"Blue Pearl Agriventures Limited",
"EFC (I) LIMITED",
"Aye Finance Limited",
"Muthoot Microfin Limited",
"Quess Corp Limited",
"CARRARO INDIA LIMITED",
"Parag Milk Foods Limited",
"MPS Limited",
"GE Power India Limited",
"GRM Overseas Ltd.",
"Bharat Bijlee Ltd.",
"Aqylon Nexus Limited",
"CITY PULSE MULTIVENTURES LIMITED",
"SAMBHV STEEL TUBES LIMITED",
"Greenply Industries Ltd",
"Jubilant Agri and Consumer Products Limited",
"Cyient DLM Limited",
"Tatva Chintan Pharma Chem Limited",
"Kewal Kiran Clothing Ltd.",
"Medi Assist Healthcare Services Limited",
"BN AGROCHEM LIMITED",
"KDDL Ltd",
"SUNDARAM-CLAYTON LIMITED",
"Bhagiradha Chemicals and Industries",
"Gateway Distriparks Limited",
"West Coast Paper Mills Limited",
"Ajmera Realty & Infra India Limited",
"Shanti Educational Initiatives Limited",
"Rossell Techsys Limited",
"ROSSARI BIOTECH LIMITED",
"Dhenu Buildcon Infra Limited",
"Universal Cables Ltd.",
"Fineotex Chemical Limited",
"Raymond Limited",
"National Standard (India) Limited",
"Bajaj Hindusthan Sugar Limited",
"FUSION FINANCE LIMITED",
"Shivalik Bimetal Controls Ltd.",
"KIRI INDUSTRIES LIMITED",
"Automotive Axles Ltd.",
"SpiceJet Limited",
"Prince Pipes and Fittings Limited",
"Globus Spirits Limited",
"Patel Engineering Ltd",
"D P ABHUSHAN LIMITED",
"DDEV PLASTIKS INDUSTRIES LIMITED",
"Indiabulls Limited",
"Premier Explosives Ltd.",
"Easy Trip Planners Limited",
"Dredging Corporation of India Ltd.",
"NRB Bearings Ltd.",
"Kilburn Engineering Ltd",
"Pokarna Ltd.",
"Deep Industries Limited",
"SIGMA ADVANCED SYSTEMS LIMITED",
"EURO PRATIK SALES LIMITED",
"Awfis Space Solutions Limited",
"Polyplex Corporation Ltd.",
"Jindal Poly Films Ltd.",
"Unichem Laboratories Ltd.",
"STANDARD ENGINEERING TECHNOLOGY LIMITED",
"INSOLATION ENERGY LIMITED",
"Hind Rectifiers Ltd.",
"Apeejay Surrendra Park Hotels Limited",
"Jindal Worldwide Ltd.",
"Arvind SmartSpaces Limited",
"Camlin Fine Sciences Ltd",
"Greenpanel Industries Limited",
"IMAGICAAWORLD ENTERTAINMENT LIMITED",
"Sanghvi Movers Ltd.",
"Rashi Peripherals Limited",
"RPSG VENTURES LIMITED",
"NOCIL Ltd",
"Dalmia Bharat Sugar and Industries Ltd",
"Siyaram Silk Mills Ltd.",
"RAVINDRA ENERGY LIMITED",
"Sirca Paints India Limited",
"Network People Services Technologies Limited",
"FISCHER MEDICAL VENTURES LIMITED",
"Vardhman Special Steels Ltd",
"GK ENERGY LIMITED",
"Ramco Industries Ltd",
"Protean eGov Technologies Limited",
"CARYSIL LIMITED",
"JASH ENGINEERING LIMITED",
"Jain Irrigation Systems Ltd.",
"HMT Limited",
"Savita Oil Technologies Limited",
"MARSONS LIMITED",
"Prataap Snacks Limited",
"JOHN COCKERILL INDIA LIMITED",
"HLE GLASCOAT LIMITED",
"JTL INDUSTRIES LIMITED",
"WELSPUN SPECIALTY SOLUTIONS LIMITED",
"Sagar Cements Ltd",
"Hikal Ltd.",
"SUNDROP BRANDS LIMITED",
"Concord Control Systems Limited",
"TCPL Packaging Limited",
"IOL Chemicals & Pharmaceuticals Ltd",
"UTKARSH SMALL FINANCE BANK LIMITED",
"Repco Home Finance Limited",
"Bombay Dyeing & Mfg. Co. Ltd.",
"SG FINSERVE LIMITED",
"Thirumalai Chemicals Ltd.",
"Federal-Mogul Goetze (India) Ltd",
"Brigade Hotel Ventures Limited",
"EPACK Durable Limited",
"Venus Pipes & Tubes Limited",
"Pennar Industries Ltd.",
"Steelcast Ltd.",
"Dr.Agarwals Eye Hospital Ltd.",
"Prakash Industries Ltd.",
"Mayur Uniquoters ltd.",
"Alembic Ltd",
"Shankara Buildpro Limited",
"Ganesha Ecosphere Limited",
"ADF Foods Limited.",
"KS Smart Technologies Limited",
"Baazar Style Retail Limited",
"Sangam (India) Ltd",
"BGR ENERGY SYSTEMS LIMITED",
"Monarch Networth Capital Limited",
"Elcid Investments Ltd.",
"Eveready Industries India Ltd.",
"Prabha Energy Limited",
"Novartis India Limited",
"Bliss GVS Pharma Limited",
"G.M. Breweries Ltd.",
"TeamLease Services Limited",
"Windsor Machines Limited",
"SPICE LOUNGE FOOD WORKS LIMITED",
"Gujarat Industries Power Co. Ltd",
"ARKADE DEVELOPERS LIMITED",
"Mangalam Cement Ltd.",
"HPL Electric & Power Limited",
"Deccan Gold Mines Ltd.",
"HONDA INDIA POWER PRODUCTS LIMITED",
"Nucleus Software Exports Ltd",
"Panacea Biotec Ltd.",
"Vimta Labs Ltd.",
"Taj GVK Hotels & Resorts Ltd.",
"Bhansali Engineering Polymers Ltd.",
"Morepen Laboratories Ltd.",
"Uniparts India Limited",
"Rajratan Global Wire Ltd",
"Rane (Madras) Ltd.",
"Jaykay Enterprises Limited",
"K.P. Energy Limited",
"IDEAFORGE TECHNOLOGY LIMITED",
"CANTABIL RETAIL INDIA LIMITED",
"Kothari Industrial Corpn. Ltd.",
"Afcom Holdings Limited",
"La Opala RG Ltd.",
"Epack Prefab Technologies Limited",
"Nitin Spinners Ltd.",
"Krsnaa Diagnostics Limited",
"Shipping Corporation of India Land and Assets Limited",
"Kalyani Investment Company Limited",
"YATRA ONLINE LIMITED",
"VINTAGE COFFEE AND BEVERAGES LIMITED",
"Sai Parenteral's Limited",
"S H Kelkar and Company Limited",
"SHRINGAR HOUSE OF MANGALSUTRA LIMITED",
"M.M.Forgings Ltd.",
"DEE DEVELOPMENT ENGINEERS LIMITED",
"TCI Express Limited",
"Rhetan TMT Limited",
"BRIGHTCOM GROUP LIMITED",
"Venky's (India) Ltd.",
"BF Utilities Ltd.",
"DIVGI TORQTRANSFER SYSTEMS LIMITED",
"Ujaas Energy Limited",
"DCX Systems Limited",
"Sasken Technologies Limited",
"Jai Corp Limited",
"Vikran Engineering Limited",
"Capacit'e Infraprojects Limited",
"Filatex India Ltd.",
"GHV INFRA PROJECTS LIMITED",
"EIH Associated Hotels Ltd.",
"Spectrum Electrical Industries Limited",
"KP GREEN ENGINEERING LIMITED",
"Apcotex Industries Limited",
"PTC India Financial Services Limited",
"Nilkamal Limited",
"Nitco Ltd.",
"Kernex Microsystems (India) Ltd.",
"Sika Interplant Systems Ltd.",
"Hindustan Oil Exploration Co. Ltd.",
"Hathway Cable & Datacom Limited",
"Indoco Remedies Ltd.",
"Pix Transmissions Ltd.",
"Studds Accessories Limited",
"Mahanagar Telephone Nigam Ltd.",
"MUFIN GREEN FINANCE LIMITED",
"MSP STEEL & POWER LTD.",
"Hindware Home Innovation Limited",
"EMS LIMITED",
"Antelopus Selan Energy Limited",
"Bajel Projects Limited",
"Insecticides India Ltd.",
"Solarworld Energy Solutions Limited",
"GSP CROP SCIENCE LIMITED",
"Mold-Tek Packaging Limited",
"Hinduja Global Solutions Limited",
"Tasty Bite Eatables Ltd.",
"Geojit Financial Services Limited",
"Mukand Ltd.",
"Indian Hume Pipe Co. Ltd.",
"Go Fashion (India) Limited",
"SUMMIT SECURITIES LTD.",
"M & B ENGINEERING LIMITED",
"SOLARA ACTIVE PHARMA SCIENCES LIMITED",
"ADVAIT ENERGY TRANSITIONS LIMITED",
"TCC CONCEPT LIMITED",
"BELDING INDIA LIMITED",
"India Pesticides Limited",
"Goodyear India Ltd.",
"S.P. Apparels Limited",
"ACCELYA SOLUTIONS INDIA LIMITED",
"Mobavenue AI Tech Limited",
"Shalby Limited",
"Veranda Learning Solutions Limited",
"NDR Auto Components Limited",
"Sai Silks (Kalamandir) Limited",
"Oriental Hotels Ltd.",
"Indo Tech Transformers Limited",
"YASHO INDUSTRIES LIMITED",
"CEINSYS TECH LIMITED",
"SATIN CREDITCARE NETWORK LIMITED",
"Ador Welding Ltd.",
"Cosmo First Limited",
"Rane Holdings Ltd.",
"India Nippon Electricals Ltd",
"INDOSOLAR LIMITED",
"STOVE KRAFT LIMITED",
"Ramco Systems Ltd",
"Shukra Pharmaceuticals Limited",
"Khazanchi Jewellers Limited",
"Delta Corp Limited",
"Indokem Ltd",
"Som Distilleries & Breweries Ltd.",
"Disa India Ltd.",
"Simplex Infrastructures Limited",
"InfoBeans Technologies Limited",
"UGRO CAPITAL LIMITED",
"Spandana Sphoorty Financial Limited",
"HI-TECH PIPES LIMITED",
"Citurgia Biochemicals Ltd.",
"WONDER ELECTRICALS LIMITED",
"LANDMARK CARS LIMITED",
"STRING METAVERSE LIMITED",
"Panama Petrochem Ltd.",
"Somany Ceramics Limited",
"Talbros Automotive Components Ltd.",
"Dollar Industries Limited",
"RAJESH POWER SERVICES LIMITED",
"Frontier Springs Ltd.",
"GRAND OAK CANYONS DISTILLERY LIMITED",
"ASIAN GRANITO INDIA LIMITED",
"R M DRIP AND SPRINKLERS SYSTEMS LIMITED",
"Windlas Biotech Limited",
"Garuda Construction and Engineering Limited",
"Dolphin Offshore Enterprises (India) Ltd.",
"SANSTAR LIMITED",
"Elpro International Ltd.",
"ALGOQUANT FINTECH LIMITED",
"Arman Financial Services Limited",
"One Mobikwik Systems Limited",
"Rishabh Instruments Limited",
"G N A Axles Limited",
"BLS E-Services Limited",
"APOLLO PIPES LIMITED",
"Stallion India Fluorochemicals Limited",
"Associated Alcohols & Breweries Ltd.",
"Silver Touch Technologies Limited",
"RICO Auto Industries Ltd.",
"Fino Payments Bank Limited",
"Balmer Lawrie Investments Ltd.",
"AAYUSH ART AND BULLION LIMITED",
"ONIX SOLAR ENERGY LIMITED",
"Digitide Solutions Limited",
"ALL TIME PLASTICS LIMITED",
"Seshasayee Paper & Boards Ltd.",
"Vindhya Telelinks Ltd.",
"Vidhi Specialty Food Ingredients Limited",
"NIBE LIMITED",
"Ashika Credit Capital Ltd.",
"TIL Ltd.",
"Sula Vineyards Limited",
"ONE POINT ONE SOLUTIONS LIMITED",
"Nelco Ltd",
"SMC Global Securities Limited",
"Jindal Drilling & Industries Ltd.",
"Dynamic Cables Limited",
"GTL Infrastructure Limited",
"Amic Forging Limited",
"Sumeet Industries Ltd.",
"BF Investment Limited",
"D-Link (India) Ltd",
"JNK India Limited",
"Suryoday Small Finance Bank Limited",
"EXICOM TELE-SYSTEMS LIMITED",
"SBC EXPORTS LIMITED",
"ASTEC LIFESCIENCES LIMITED",
"MAGELLANIC CLOUD LIMITED",
"Godavari Biorefineries Limited",
"Sportking India Ltd.",
"DCW Ltd.",
"GYFTR LIMITED",
"Jagran Prakashan Limited",
"SHANTI GOLD INTERNATIONAL LIMITED",
"RIR POWER ELECTRONICS LIMITED",
"Navkar Corporation Limited",
"Yash Highvoltage Limited",
"Kwality Pharmaceuticals Limited",
"SURAKSHA DIAGNOSTIC LIMITED",
"Haryana Financial Corporation Ltd.",
"AVISHKAR INFRA REALTY LIMITED",
"RACL Geartech Limited",
"J.G.Chemicals Limited",
"Wendt (India) Ltd.",
"GOCL Corporation Limited",
"Pashupati Cotspin Limited",
"Precision Camshafts Limited",
"Gandhar Oil Refinery (India) Limited",
"GPT Infraprojects Limited",
"Mahamaya Steel Industries Limited",
"Orient Technologies Limited",
"HUHTAMAKI INDIA LIMITED",
"OMAXE LIMITED",
"SPML Infra Limited",
"DOLAT ALGOTECH LIMITED",
"Meghmani Organics Limited",
"Confidence Petroleum India Limited",
"Antony Waste Handling Cell Limited",
"PNB Gilts Ltd.",
"Shriram Properties Limited",
"Salasar Techno Engineering Limited",
"Amir Chand Jagdish Kumar (Exports) Limited",
"KMC Speciality Hospitals India Limited",
"DEN Networks Limited",
"ESAF Small Finance Bank Ltd",
"Motisons Jewellers Limited",
"Punjab Chemicals and Crop Protection Ltd.",
"IVALUE INFOSOLUTIONS LIMITED",
"EXPLEO SOLUTIONS LIMITED",
"Aurum PropTech Limited",
"SEPC LIMITED",
"Arfin India Limited",
"Hester Biosciences Ltd",
"Meghna Infracon Infrastructure Limited",
"Dynacons Systems & Solutions Ltd.",
"TTK Healthcare Ltd.",
"Jyoti Structures Ltd.",
"Unitech Ltd.",
"Titan Bio-Tech Ltd.",
"Genesys International Corporation Ltd.",
"HMA Agro Industries Limited",
"Jindal Photo Limited",
"Blue Cloud Softech Solutions Limited",
"VIDYA WIRES LIMITED",
"Chaman Lal Setia Exports Ltd.",
"ANDHRA PAPER LIMITED",
"Tinna Rubber and Infrastructure Limited",
"ASIAN ENERGY SERVICES LTD",
"IFGL Refractories Limited",
"Allcargo Logistics Ltd",
"CFF FLUID CONTROL LIMITED",
"Everest Kanto Cylinders Ltd.",
"Bharat Wire Ropes Limited",
"Signpost India Limited",
"Syncom Formulations (India) Ltd.",
"Jagsonpal Pharmaceuticals Limited",
"Platinum Industries Limited",
"Orient Green Power Company Limited",
"Systematix Corporate Services Ltd.",
"Walchandnagar Industries Ltd",
"Atul Auto Limited",
"Manaksia Coated Metals & Industries Ltd",
"Benares Hotels Ltd",
"Alldigi Tech Limited",
"Texmaco Infrastructure & Holdings Ltd",
"Gujarat Natural Resources Limited",
"A-1 LIMITED",
"Kross Limited",
"NGL Fine Chem Ltd.",
"Himatsingka Seide Ltd.",
"PAUSHAK LIMITED (formerly known as Darshak Limited)",
"Saraswati Commercial (India) Ltd.",
"PNGS Reva Diamond Jewellery Limited",
"Monte Carlo Fashions Limited",
"The Hi-Tech Gears Limited",
"Ultramarine & Pigments Ltd.",
"5paisa Capital Limited",
"Quadrant Future Tek Limited",
"Alicon Castalloy Limited",
"Modern Insulators Ltd.",
"RENAISSANCE GLOBAL LIMITED",
"DAM Capital Advisors Limited",
"Igarashi Motors India Ltd.",
"Raj Rayon Industries Limited",
"Paramount Communications Ltd.",
"IG Petrochemicals Ltd",
"Media Matrix Worldwide Ltd.",
"Centrum Capital Limited",
"IKIO Technologies Limited",
"CAPITAL INDIA FINANCE LIMITED",
"Balaji Telefilms Ltd.",
"Capital Small Finance Bank Ltd",
"Arihant Superstructures Limited",
"BHARAT GLOBAL DEVELOPERS LIMITED",
"3B BlackBio Dx Limited",
"Laxmi Dental Limited",
"RUPA & COMPANY LIMITED",
"Excell Industries Ltd.",
"Rama Steel Tubes Limited",
"UNICOMMERCE ESOLUTIONS LIMITED",
"Apis India Ltd",
"B L Kashyap and Sons Ltd",
"RRP DEFENSE LIMITED",
"Apex Frozen Foods Limited",
"Virtuoso Optoelectronics Limited",
"BIRLANU LIMITED",
"Jyoti Resins & Adhesives Ltd",
"JINDAL POLY INVESTMENT AND FINANCE COMPANY LIMITED",
"Master Trust Ltd.",
"Venus Remedies Ltd.",
"Reliance Industrial Infrastructure",
"Lincoln Pharmaceuticals Ltd.",
"Shree Pushkar Chemicals & Fertilisers Limited",
"Mangalam Worldwide Limited",
"Butterfly Gandhimathi Appliances Limited",
"Roto Pumps Ltd.",
"Salzer Electronics Ltd.",
"Shree Digvijay Cement Co. Ltd.",
"Rajoo Engineers Ltd.",
"Finkurve Financial Services Limited",
"Bajaj Healthcare Limited",
"Tarsons Products Limited",
"A B INFRABUILD LIMITED",
"IZMO Limited",
"STL Networks Limited",
"Faze Three Ltd.",
"Western Carriers (India) Limited",
"AYM Syntex Limited",
"Suraj Estate Developers Limited",
"Steel Exchange India Ltd.",
"Hariom Pipe Industries Limited",
"GPT Healthcare Limited",
"Updater Services Limited",
"Bharat Seats Ltd",
"SRM CONTRACTORS LIMITED",
"PANORAMA STUDIOS INTERNATIONAL LIMITED",
"Quick Heal Technologies Limited",
"Andrew Yule & Company Ltd",
"Vardhman Holdings Limited",
"Diffusion Engineers Limited",
"Valiant Communications Ltd.",
"Automobile Corpn. of Goa Ltd.",
"TGV SRAAC LIMITED",
"RAJPUTANA STAINLESS LIMITED",
"Jaro Institute of Technology Management and Research Limited",
"ZUARI AGRO CHEMICALS LIMITED",
"Control Print (India) Ltd.",
"IRM ENERGY LIMITED",
"Indo Rama Synthetics (India) Ltd.",
"Arihant Foundations & Housing Ltd.",
"Mirc Electronics Ltd",
"Yuken India Ltd.",
"Nelcast Limited",
"Borosil Scientific Limited",
"Dhanlaxmi Bank Limited",
"Ind-Swift Laboratories Ltd.",
"Ratnaveer Precision Engineering Limited",
"ABANS FINANCIAL SERVICES LIMITED",
"CROPSTER AGRO LIMITED",
"CREST VENTURES LIMITED",
"Bhartiya International Ltd.",
"NIIT Ltd.",
"Asian Star Co. Ltd.",
"Kalind Limited",
"Jay Bharat Maruti Ltd.",
"BOMBAY SUPER HYBRID SEEDS LIMITED",
"Tribhovandas Bhimji Zaveri Limited",
"UNITED FOODBRANDS LIMITED",
"Pervasive Commodities Limited",
"Advent Hotels International Limited",
"Oricon Enterprises Ltd.",
"Matrimony.com Limited",
"Jaybharat Textiles And Real Estate Limited",

    ]
    USE_LIVE_BOOTSTRAP = os.environ.get("USE_LIVE_BOOTSTRAP", "0") == "1"
